const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SIZE=15, values={A:1,B:3,C:3,D:2,E:1,F:4,G:2,H:4,I:1,J:8,K:5,L:1,M:3,N:1,O:1,P:3,Q:10,R:1,S:1,T:1,U:1,V:4,W:4,X:8,Y:4,Z:10};
const freq={A:18,B:4,C:4,D:8,E:24,F:4,G:6,H:4,I:18,J:2,K:2,L:8,M:4,N:12,O:16,P:4,Q:2,R:12,S:8,T:12,U:8,V:4,W:4,X:2,Y:4,Z:2};
const fallback=["ABLE","ABOUT","ABOVE","ACT","ADD","AGE","AIR","ALSO","AMONG","APPLE","AREA","ASK","BACK","BALL","BANK","BASE","BEAR","BEAT","BEST","BIRD","BLUE","BOARD","BOOK","BRAIN","BUILD","CALL","CARE","CAT","CHANGE","CITY","CLASS","CLEAR","CLOUD","CODE","COLD","COME","CREATE","DANCE","DARK","DAY","DEEP","DOG","DREAM","EARTH","EASY","EDGE","EDUCATION","ENERGY","ENJOY","EVERY","FAMILY","FAST","FIRE","FLOW","FOOD","GAME","GARDEN","GIVE","GOOD","GREAT","GREEN","GROUP","GROW","HAPPY","HEART","HELP","HOME","IDEA","JOY","KEEP","KIND","KNOW","LEARN","LIGHT","LINE","LOVE","MAKE","MIND","MOVE","MUSIC","NAME","NEW","NIGHT","OPEN","PEACE","PEOPLE","PLACE","PLAY","POWER","PROMPT","READ","RIVER","ROAD","SCHOOL","SHARE","SMART","SMILE","SONG","STAR","START","STORY","STRONG","SUN","TEAM","THINK","TIME","TOOL","TREE","VALUE","VOICE","WATER","WAY","WORD","WORK","WORLD","WRITE"];
let board=[],rack=[],bag=[],selected=null,placed=[],scores=[0,0],turn=0,time=1200,timer,history=[];
function bonus(r,c){const corner=(r==0||r==7||r==14)&&(c==0||c==7||c==14);if((r==c||r+c==14)&&[0,7,14].includes(r))return r==7&&c==7?"dw":"tw";if((r+c)%11==0)return"tl";if((r*3+c*5)%17==0)return"dl";return""}
function buildBoard(){board=Array.from({length:SIZE},()=>Array(SIZE).fill(null));const el=$("#board");el.innerHTML="";for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){let d=document.createElement("div"),b=bonus(r,c);d.className="cell "+b+(r==7&&c==7?" center":"");d.dataset.r=r;d.dataset.c=c;d.title=b?b.toUpperCase():"";d.onclick=()=>place(r,c);el.appendChild(d)}}
function makeBag(){bag=[];for(const [l,n] of Object.entries(freq))for(let i=0;i<n;i++)bag.push(l);shuffleArray(bag)}
function draw(){while(rack.length<15&&bag.length)rack.push(bag.pop());renderRack()}
function shuffleArray(a){for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function tile(l){let d=document.createElement("div");d.className="tile";d.innerHTML=l+"<small>"+values[l]+"</small>";return d}
function renderRack(){let e=$("#rack");e.innerHTML="";rack.forEach((l,i)=>{let d=tile(l);if(i===selected)d.classList.add("selected");d.onclick=()=>{selected=selected===i?null:i;renderRack()};e.appendChild(d)})}
function renderBoard(){ $$(".cell").forEach(x=>{let r=+x.dataset.r,c=+x.dataset.c,l=board[r][c];x.innerHTML="";if(l)x.appendChild(tile(l))})}
function place(r,c){if(selected===null||board[r][c])return;let l=rack[selected];board[r][c]=l;placed.push({r,c,l});rack.splice(selected,1);selected=null;renderBoard();renderRack()}
function recall(){placed.slice().reverse().forEach(p=>{board[p.r][p.c]=null;rack.push(p.l)});placed=[];renderBoard();renderRack()}
function formedWord(){if(!placed.length)return null;let rows=new Set(placed.map(p=>p.r)),cols=new Set(placed.map(p=>p.c));if(rows.size>1&&cols.size>1)return null;let horiz=rows.size===1,r=horiz?placed[0].r:Math.min(...placed.map(p=>p.r)),c=horiz?Math.min(...placed.map(p=>p.c)):placed[0].c;while((horiz?c:r)>0&&board[horiz?r:r-1][horiz?c-1:c])horiz?c--:r--;let word="",cells=[];while(r<SIZE&&c<SIZE&&board[r][c]){word+=board[r][c];cells.push({r,c});horiz?c++:r++}return word.length?{word,cells}:null}
function scoreWord(w){let total=0,mult=1;w.cells.forEach(x=>{let v=values[board[x.r][x.c]],fresh=placed.some(p=>p.r===x.r&&p.c===x.c),b=fresh?bonus(x.r,x.c):"";if(b==="dl")v*=2;if(b==="tl")v*=3;if(b==="dw")mult*=2;if(b==="tw")mult*=3;total+=v});return total*mult+(placed.length===15?75:0)}
async function valid(word){if(word.length<2)return false;if(fallback.includes(word))return true;try{let r=await fetch("https://api.dictionaryapi.dev/api/v2/entries/en/"+word.toLowerCase());return r.ok}catch{return true}}
function log(s){history.unshift(s);$("#log").innerHTML=history.slice(0,20).map(x=>'<div class="logitem">'+x+"</div>").join("")}
async function submit(){let w=formedWord();if(!w){setStatus("Place tiles in one continuous row or column.");return}if(!(await valid(w.word))){setStatus(w.word+" was not found. Recall or adjust the move.");return}let pts=scoreWord(w);scores[turn]+=pts;$("#pScore").textContent=scores[0];$("#aScore").textContent=scores[1];log((turn?"AI":"You")+" played "+w.word+" for "+pts+" points.");placed=[];draw();lookupWord(w.word);if($("#mode").value==="Human vs AI"){turn=1;setStatus("AI is thinking…");setTimeout(aiTurn,650)}else{turn=1-turn;setStatus("Move accepted.")}saveStats(w.word,pts)}
function aiTurn(){let choices=fallback.filter(w=>w.length<=rack.length&&canMake(w,rack));let word=choices.sort((a,b)=>b.length-a.length)[0];if(!word){log("AI passed.");turn=0;setStatus("Your turn.");return}let row=board.flat().some(Boolean)?findEmptyRow(word.length):7,start=Math.floor((15-word.length)/2);let used=[];for(let i=0;i<word.length;i++){let ix=rack.indexOf(word[i]);if(ix<0)break;board[row][start+i]=word[i];used.push(ix);rack.splice(ix,1)}let cells=[...word].map((_,i)=>({r:row,c:start+i}));let pts=cells.reduce((s,x)=>s+values[board[x.r][x.c]],0);scores[1]+=pts;$("#aScore").textContent=scores[1];renderBoard();draw();log("AI played "+word+" for "+pts+" points.");turn=0;setStatus("Your turn.");lookupWord(word)}
function canMake(w,r){let a=[...r];return [...w].every(l=>{let i=a.indexOf(l);if(i<0)return false;a.splice(i,1);return true})}
function findEmptyRow(n){for(let r=0;r<15;r++){let ok=true;for(let c=0;c<n;c++)if(board[r][c])ok=false;if(ok)return r}return 14}
async function lookupWord(word,target="#definition"){let e=$(target);e.innerHTML="<p>Discovering <b>"+word+"</b>…</p>";try{let r=await fetch("https://api.dictionaryapi.dev/api/v2/entries/en/"+word.toLowerCase());if(!r.ok)throw 0;let d=(await r.json())[0],m=d.meanings?.[0],def=m?.definitions?.[0];e.innerHTML="<h3>"+d.word.toUpperCase()+"</h3><p>"+(d.phonetic||"")+"</p><p><b>"+(m?.partOfSpeech||"Word")+"</b> — "+(def?.definition||"Definition unavailable.")+"</p><button onclick=\"saveWord('"+d.word+"')\">SAVE WORD</button>"}catch{e.innerHTML="<p><b>"+word.toUpperCase()+"</b><br>Dictionary discovery is unavailable right now. Gameplay remains available.</p>"}}
function saveWord(w){let a=JSON.parse(localStorage.waWords||"[]");if(!a.includes(w))a.push(w);localStorage.waWords=JSON.stringify(a);showWords()}
function showWords(){let a=JSON.parse(localStorage.waWords||"[]");$("#savedWords").innerHTML=a.length?a.map(x=>"<button onclick=\"lookupWord('"+x+"','#learnDefinition')\">"+x+"</button>").join(" "):"No saved words yet."}
function saveStats(word,pts){let s=JSON.parse(localStorage.waStats||'{"games":0,"best":0,"word":""}');if(pts>s.best){s.best=pts;s.word=word}localStorage.waStats=JSON.stringify(s);leaders()}
function leaders(){let s=JSON.parse(localStorage.waStats||'{"games":0,"best":0,"word":""}');$("#leaderboard").innerHTML="<h3>Player</h3><p>Best word: <b>"+(s.word||"—")+"</b> &nbsp; Best word score: <b>"+s.best+"</b></p><p>Scores are stored privately in this browser.</p>"}
function setStatus(s){$("#status").textContent=s}
function newGame(){clearInterval(timer);scores=[0,0];turn=0;placed=[];history=[];$("#pScore").textContent=$("#aScore").textContent=0;$("#log").innerHTML="";buildBoard();makeBag();rack=[];draw();time=1200;timer=setInterval(()=>{time=Math.max(0,time-1);$("#clock").textContent=String(Math.floor(time/60)).padStart(2,"0")+":"+String(time%60).padStart(2,"0")},1000);setStatus("Your turn. Select a tile, then a board square.")}
$$("nav button").forEach(b=>b.onclick=()=>{$$("nav button,.tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tab).classList.add("active")});
$("#newGame").onclick=newGame;$("#submit").onclick=submit;$("#recall").onclick=recall;$("#shuffle").onclick=()=>{shuffleArray(rack);renderRack()};$("#pass").onclick=()=>{recall();log("Turn passed.");setStatus("Turn passed.")};$("#exchange").onclick=()=>{recall();rack.forEach(x=>bag.unshift(x));rack=[];shuffleArray(bag);draw();log("Rack exchanged.")};$("#hint").onclick=()=>{let w=fallback.find(w=>canMake(w,rack));setStatus(w?"Coach hint: your rack can form “"+w+"”.":"Coach: look for short connecting words.")};
$("#discover").onclick=()=>lookupWord($("#lookup").value);$("#learnDiscover").onclick=()=>lookupWord($("#learnLookup").value,"#learnDefinition");
$("#difficulty").onchange=e=>{let i=["Beginner","Intermediate","Advanced","Expert","Grandmaster"].indexOf(e.target.value);$("#diffNeedle").style.transform="rotate("+(-60+i*30)+"deg)"};
$("#startDemo").onclick=()=>{let feed=$("#demoFeed"),i=0,words=["LEARN","SMART","WORD","POWER","CREATE","VALUE"];feed.innerHTML="Starting "+$("#demoLevel").value+" AI exhibition…";let x=setInterval(()=>{if(i>=words.length){clearInterval(x);feed.innerHTML+="<p><b>Demo complete.</b> Replay at another difficulty or enter Play mode.</p>";return}feed.innerHTML+="<p>Move "+(i+1)+": AI "+(i%2+1)+" evaluates the rack and selects <b>"+words[i]+"</b>.</p>";i++},900)};
$("#certName").oninput=e=>$("#certPlayer").textContent=e.target.value.toUpperCase();$("#certId").textContent="Certificate ID: WA15-"+Date.now().toString(36).toUpperCase();$("#printCert").onclick=()=>print();$("#emailCert").onclick=()=>location.href="mailto:?subject=My WordArena 15 Certificate&body=I earned a WordArena 15 vocabulary and strategy certificate at BillionPrompts.ai.";
showWords();leaders();newGame();